version: "3.9"

services:
  postgres:
    image: docker.io/postgres:15
    container_name: netbox-postgres
    restart: unless-stopped
    env_file:
      - ./env/postgres.env
    volumes:
      - /share/Local/netbox/postgres:/var/lib/postgresql/data
    networks:
      Vlan1:
        ipv4_address: 172.31.240.61

  redis:
  image: redis:7
  container_name: netbox-redis
  restart: unless-stopped
  env_file:
    - ./env/redis.env
  command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  volumes:
    - /share/Container/netbox/redis:/data
  networks:
    Vlan1:
      ipv4_address: 172.31.240.60
      
  redis-cache:
    image: docker.io/redis:7
    container_name: netbox-redis-cache
    restart: unless-stopped
    env_file:
      - ./env/redis-cache.env
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - /share/Container/netbox/redis-cache:/data
    networks:
      Vlan1:
        ipv4_address: 172.31.240.59

  netbox:
    image: docker.io/netboxcommunity/netbox:v4.4-3.4.1
    container_name: netbox
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - redis-cache
    env_file:
      - ./env/netbox.env
    volumes:
      - /share/Container/netbox/media:/opt/netbox/netbox/media
      - /share/Container/netbox/reports:/opt/netbox/netbox/reports
      - /share/Container/netbox/scripts:/opt/netbox/netbox/scripts
      - /share/Container/netbox/configuration:/etc/netbox/config:rw
    networks:
      Vlan1:
        ipv4_address: 172.31.240.62

networks:
  Vlan1:
    external: true
