version: "3.8"

services:
  postgres:
    image: docker.io/postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./env/postgres.env
    volumes:
      - /share/Local/netbox/postgres:/var/lib/postgresql/data
    networks:
      Vlan1:
        ipv4_address: 172.31.240.61

  redis:
    image: docker.io/redis:7
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "H733Kdjndks81"]
    volumes:
      - /share/Container/netbox/redis:/data
    networks:
      Vlan1:
        ipv4_address: 172.31.240.60

  redis-cache:
    image: docker.io/redis:7
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "t4Ph722qJ5QHeQ1qfu36"]
    volumes:
      - /share/Container/netbox/redis-cache:/data
    networks:
      Vlan1:
        ipv4_address: 172.31.240.59

  netbox:
    image: docker.io/netboxcommunity/netbox:v4.4-3.4.1
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - redis-cache
    env_file:
      - ./env/netbox.env
    volumes:
      - /share/Container/netbox/configuration:/etc/netbox/config:rw
      - /share/Container/netbox/media:/opt/netbox/netbox/media:rw
      - /share/Container/netbox/reports:/opt/netbox/netbox/reports:rw
      - /share/Container/netbox/scripts:/opt/netbox/netbox/scripts:rw
    networks:
      Vlan1:
        ipv4_address: 172.31.240.62

  netbox-worker:
    image: docker.io/netboxcommunity/netbox:v4.4-3.4.1
    restart: unless-stopped
    depends_on:
      - netbox
    env_file:
      - ./env/netbox.env
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    networks:
      Vlan1:
        ipv4_address: 172.31.240.58

networks:
  Vlan1:
    external: true
